import {
  Exercise,
  Routine,
  WorkoutSession,
  WorkoutExercise,
  WorkoutSet,
} from '../types'

// Mock Exercise Library
export const mockExercises: Exercise[] = [
  {
    id: 'exercise-1',
    name: 'Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'deltoids'],
    equipment: 'barbell',
    isCustom: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'exercise-2',
    name: 'Chest Flyes',
    category: 'chest',
    muscleGroups: ['chest'],
    equipment: 'dumbbell',
    isCustom: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'exercise-3',
    name: 'Incline Press',
    category: 'chest',
    muscleGroups: ['chest', 'deltoids'],
    equipment: 'dumbbell',
    isCustom: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'exercise-4',
    name: 'Cable Crossover',
    category: 'chest',
    muscleGroups: ['chest'],
    equipment: 'cable',
    isCustom: false,
    createdAt: new Date('2024-01-01'),
  },
]

// Mock Routine
export const mockRoutine: Routine = {
  id: 'routine-1',
  userId: 'user-1',
  name: 'Push Day',
  description: 'Chest, shoulders, and triceps workout',
  exercises: [
    {
      id: 'routine-exercise-1',
      routineId: 'routine-1',
      exerciseId: 'exercise-1',
      order: 0,
      targetSets: 4,
      targetReps: 8,
      targetWeight: 135,
      weightUnit: 'lbs',
      restTime: 90,
    },
    {
      id: 'routine-exercise-2',
      routineId: 'routine-1',
      exerciseId: 'exercise-2',
      order: 1,
      targetSets: 4,
      targetReps: 8,
      targetWeight: 145,
      weightUnit: 'lbs',
      restTime: 60,
    },
    {
      id: 'routine-exercise-3',
      routineId: 'routine-1',
      exerciseId: 'exercise-3',
      order: 2,
      targetSets: 3,
      targetReps: 10,
      targetWeight: 60,
      weightUnit: 'lbs',
      restTime: 60,
    },
    {
      id: 'routine-exercise-4',
      routineId: 'routine-1',
      exerciseId: 'exercise-4',
      order: 3,
      targetSets: 3,
      targetReps: 12,
      targetWeight: 40,
      weightUnit: 'lbs',
      restTime: 60,
    },
  ],
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  isActive: true,
}

// Mock Workout Session
export const mockWorkoutSession: WorkoutSession = {
  id: 'session-1',
  userId: 'user-1',
  routineId: 'routine-1',
  routineName: 'Push Day',
  status: 'in-progress',
  startTime: new Date(),
  currentExerciseIndex: 1, // Currently on Chest Flyes (0-indexed)
  exercises: [
    {
      id: 'workout-exercise-1',
      sessionId: 'session-1',
      exerciseId: 'exercise-1',
      exerciseName: 'Bench Press',
      order: 0,
      status: 'completed',
      startTime: new Date(),
      endTime: new Date(),
      sets: [
        {
          id: 'set-1-1',
          workoutExerciseId: 'workout-exercise-1',
          setNumber: 1,
          targetReps: 8,
          actualReps: 8,
          targetWeight: 135,
          actualWeight: 135,
          weightUnit: 'lbs',
          status: 'completed',
          completedAt: new Date(),
        },
        {
          id: 'set-1-2',
          workoutExerciseId: 'workout-exercise-1',
          setNumber: 2,
          targetReps: 8,
          actualReps: 8,
          targetWeight: 135,
          actualWeight: 135,
          weightUnit: 'lbs',
          status: 'completed',
          completedAt: new Date(),
        },
        {
          id: 'set-1-3',
          workoutExerciseId: 'workout-exercise-1',
          setNumber: 3,
          targetReps: 8,
          actualReps: 7,
          targetWeight: 135,
          actualWeight: 135,
          weightUnit: 'lbs',
          status: 'completed',
          completedAt: new Date(),
        },
        {
          id: 'set-1-4',
          workoutExerciseId: 'workout-exercise-1',
          setNumber: 4,
          targetReps: 8,
          actualReps: 8,
          targetWeight: 135,
          actualWeight: 135,
          weightUnit: 'lbs',
          status: 'completed',
          completedAt: new Date(),
        },
      ],
    },
    {
      id: 'workout-exercise-2',
      sessionId: 'session-1',
      exerciseId: 'exercise-2',
      exerciseName: 'Chest Flyes',
      order: 1,
      status: 'in-progress',
      startTime: new Date(),
      sets: [
        {
          id: 'set-2-1',
          workoutExerciseId: 'workout-exercise-2',
          setNumber: 1,
          targetReps: 8,
          actualReps: 8,
          targetWeight: 145,
          actualWeight: 145,
          weightUnit: 'lbs',
          status: 'completed',
          completedAt: new Date(),
        },
        {
          id: 'set-2-2',
          workoutExerciseId: 'workout-exercise-2',
          setNumber: 2,
          targetReps: 8,
          actualReps: undefined,
          targetWeight: 145,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
        {
          id: 'set-2-3',
          workoutExerciseId: 'workout-exercise-2',
          setNumber: 3,
          targetReps: 8,
          actualReps: undefined,
          targetWeight: 145,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
        {
          id: 'set-2-4',
          workoutExerciseId: 'workout-exercise-2',
          setNumber: 4,
          targetReps: 8,
          actualReps: undefined,
          targetWeight: 145,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
      ],
    },
    {
      id: 'workout-exercise-3',
      sessionId: 'session-1',
      exerciseId: 'exercise-3',
      exerciseName: 'Incline Press',
      order: 2,
      status: 'not-started',
      sets: [
        {
          id: 'set-3-1',
          workoutExerciseId: 'workout-exercise-3',
          setNumber: 1,
          targetReps: 10,
          actualReps: undefined,
          targetWeight: 60,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
        {
          id: 'set-3-2',
          workoutExerciseId: 'workout-exercise-3',
          setNumber: 2,
          targetReps: 10,
          actualReps: undefined,
          targetWeight: 60,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
        {
          id: 'set-3-3',
          workoutExerciseId: 'workout-exercise-3',
          setNumber: 3,
          targetReps: 10,
          actualReps: undefined,
          targetWeight: 60,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
      ],
    },
    {
      id: 'workout-exercise-4',
      sessionId: 'session-1',
      exerciseId: 'exercise-4',
      exerciseName: 'Cable Crossover',
      order: 3,
      status: 'not-started',
      sets: [
        {
          id: 'set-4-1',
          workoutExerciseId: 'workout-exercise-4',
          setNumber: 1,
          targetReps: 12,
          actualReps: undefined,
          targetWeight: 40,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
        {
          id: 'set-4-2',
          workoutExerciseId: 'workout-exercise-4',
          setNumber: 2,
          targetReps: 12,
          actualReps: undefined,
          targetWeight: 40,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
        {
          id: 'set-4-3',
          workoutExerciseId: 'workout-exercise-4',
          setNumber: 3,
          targetReps: 12,
          actualReps: undefined,
          targetWeight: 40,
          actualWeight: undefined,
          weightUnit: 'lbs',
          status: 'incomplete',
        },
      ],
    },
  ],
  createdAt: new Date(),
  updatedAt: new Date(),
}
